steps:
  # 1. Artifact Registry에 업로드할 Docker 이미지 빌드
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '--build-arg', 'NEXT_PUBLIC_API_URL=$_NEXT_PUBLIC_API_URL',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:latest',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:$COMMIT_SHA',
      '.'
    ]

  # 2. 빌드된 도커 이미지를 Artifact Registry로 푸시
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:latest'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:$COMMIT_SHA'
    ]

  # 3. Google Cloud Run에 도커 컨테이너 서비스 배포
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'tones-frontend',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:$COMMIT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated',
      '--port', '3000',
      '--min-instances', '0',
      '--max-instances', '3',
      '--cpu', '1',
      '--memory', '512Mi',
    ]

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:latest'
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/tones-repo/tones-frontend:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY
